/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as MapRouteImport } from './routes/map'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as FarmsIndexRouteImport } from './routes/farms.index'
import { Route as FarmsFarmIdRouteImport } from './routes/farms.$farmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsFarmIdRoute = FarmsFarmIdRouteImport.update({
  id: '/farms/$farmId',
  path: '/farms/$farmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/farmer': typeof FarmerRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms/': typeof FarmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/farmer': typeof FarmerRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms': typeof FarmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/farmer': typeof FarmerRoute
  '/map': typeof MapRoute
  '/plan': typeof PlanRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms/': typeof FarmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/events'
    | '/farmer'
    | '/map'
    | '/plan'
    | '/farms/$farmId'
    | '/farms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/events'
    | '/farmer'
    | '/map'
    | '/plan'
    | '/farms/$farmId'
    | '/farms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/events'
    | '/farmer'
    | '/map'
    | '/plan'
    | '/farms/$farmId'
    | '/farms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  EventsRoute: typeof EventsRoute
  FarmerRoute: typeof FarmerRoute
  MapRoute: typeof MapRoute
  PlanRoute: typeof PlanRoute
  FarmsFarmIdRoute: typeof FarmsFarmIdRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/': {
      id: '/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$farmId': {
      id: '/farms/$farmId'
      path: '/farms/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof FarmsFarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  EventsRoute: EventsRoute,
  FarmerRoute: FarmerRoute,
  MapRoute: MapRoute,
  PlanRoute: PlanRoute,
  FarmsFarmIdRoute: FarmsFarmIdRoute,
  FarmsIndexRoute: FarmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
